// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(WeatherForecastDbContext))]
    partial class WeatherForecastDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.WeatherForecast", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("integer");

                    b.HasKey("Date");

                    b.ToTable("WeatherForecasts");

                    b.HasData(
                        new
                        {
                            Date = new DateTime(2023, 1, 12, 19, 22, 22, 548, DateTimeKind.Local).AddTicks(5478),
                            Summary = "Freezing",
                            TemperatureC = 0
                        },
                        new
                        {
                            Date = new DateTime(2023, 1, 13, 19, 22, 22, 548, DateTimeKind.Local).AddTicks(5510),
                            Summary = "Bracing",
                            TemperatureC = 1
                        },
                        new
                        {
                            Date = new DateTime(2023, 1, 14, 19, 22, 22, 548, DateTimeKind.Local).AddTicks(5513),
                            Summary = "Chilly",
                            TemperatureC = 2
                        },
                        new
                        {
                            Date = new DateTime(2023, 1, 15, 19, 22, 22, 548, DateTimeKind.Local).AddTicks(5515),
                            Summary = "Cool",
                            TemperatureC = 3
                        },
                        new
                        {
                            Date = new DateTime(2023, 1, 16, 19, 22, 22, 548, DateTimeKind.Local).AddTicks(5517),
                            Summary = "Mild",
                            TemperatureC = 4
                        },
                        new
                        {
                            Date = new DateTime(2023, 1, 17, 19, 22, 22, 548, DateTimeKind.Local).AddTicks(5520),
                            Summary = "Warm",
                            TemperatureC = 5
                        },
                        new
                        {
                            Date = new DateTime(2023, 1, 18, 19, 22, 22, 548, DateTimeKind.Local).AddTicks(5522),
                            Summary = "Balmy",
                            TemperatureC = 6
                        },
                        new
                        {
                            Date = new DateTime(2023, 1, 19, 19, 22, 22, 548, DateTimeKind.Local).AddTicks(5524),
                            Summary = "Hot",
                            TemperatureC = 7
                        },
                        new
                        {
                            Date = new DateTime(2023, 1, 20, 19, 22, 22, 548, DateTimeKind.Local).AddTicks(5527),
                            Summary = "Sweltering",
                            TemperatureC = 8
                        },
                        new
                        {
                            Date = new DateTime(2023, 1, 21, 19, 22, 22, 548, DateTimeKind.Local).AddTicks(5529),
                            Summary = "Scorching",
                            TemperatureC = 9
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
